### ISSUE TITLE
Enabling HTTPS

### ISSUE THREAD

**Issue by NickCraver** [caffeinewriter/Emoji-Ipsum#6]
Now that GitHub Pages supports HTTPS, can we please enable the "Enforce HTTPS" setting under this repo's settings? People need secure emoji!

**Comment by caffeinewriter** [comment]
Ask, and you shall receive! I've enabled "Enforce HTTPS", though it appears it might take some time to take effect. Thanks for the reminder! I'll close this once I verify it's actually enforcing it.

**Comment by caffeinewriter** [comment]
Looks like it's enforcing it now. Thanks again!

**Comment by NickCraver** [comment]
\o/ Thanks!

Follow-up note: the site configured in github is https://emojiipsum.top/, instead of https://www.emojiipsum.top/ but there doesn't appear to be a non-`www.` entry anywhere. Mind tweaking that to the `www.` link directly?

**Comment by caffeinewriter** [comment]
Yep! I have a simple redirect for `@` set up through Namecheap, but it doesn't work with HTTPS, since I don't think it automatically issues certificates. So I've just changed the link to link directly to `www`. :)
